defmodule FountainWeb.Endpoint do
  @moduledoc false
  use Phoenix.Endpoint, otp_app: :fountain

  @doc """
  CIDRs treated as proxies when walking X-Forwarded-For.

  Defaults to the k3s pod and service networks plus loopback. Deliberately not
  all of RFC1918: LAN clients reach this deployment directly, and trusting
  192.168/16 would step over the very addresses being rate-limited.
  """
  def trusted_proxies do
    Application.get_env(:fountain, :trusted_proxies, [
      "10.42.0.0/16",
      "10.43.0.0/16",
      "127.0.0.1/32",
      "::1/128"
    ])
  end

  # `secure` is set from config rather than hardcoded: a self-hosted instance on
  # plain http (the compose default) would never receive a cookie marked secure,
  # so it cannot simply be true. runtime.exs turns it on whenever PUBLIC_URL is
  # https, which is every deployment that can actually honour it.
  #
  # Signed, not encrypted. The contents are readable but not forgeable, and today
  # that is a user id and a session version counter. Adding an encryption_salt
  # would log every existing session out to hide two values that are already
  # tamper-proof — worth doing alongside the first change that puts anything
  # else in here, not on its own.
  @session_options [
    store: :cookie,
    key: "_fountain_key",
    signing_salt: "0O7/IE2U",
    same_site: "Lax"
  ]

  # peer_data + x_headers so LiveView can resolve a client address for audit
  # events. Without them every UI-originated audit row has a nil request_ip,
  # which is most of the value of auditing the UI in the first place.
  @connect_info [session: @session_options, peer_data: true, x_headers: true]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: @connect_info],
    longpoll: [connect_info: @connect_info]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fountain,
    gzip: not code_reloading?,
    only: FountainWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fountain
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  # Resolve the real client address before anything keys on it. Fountain sits
  # behind Traefik, so conn.remote_ip is the ingress pod — which made every
  # per-IP rate-limit bucket effectively global and every audit row attribute to
  # the proxy.
  #
  # The forwarding header is only honoured for connections that actually came
  # from a trusted proxy — see the plug's moduledoc for why that check cannot be
  # left to RemoteIp.
  plug FountainWeb.Plugs.ClientIp
  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # body_reader caches the raw request body in conn.assigns[:raw_body] before
  # Plug.Parsers consumes it. Required for Stripe webhook signature verification
  # in FountainWeb.StripeWebhookController.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {FountainWeb.CachingBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  # Not `plug Plug.Session, @session_options`: the `secure` flag has to be
  # decided at runtime. A release is one artifact, and the same artifact runs
  # the hosted instance behind TLS and a self-hoster's compose stack on plain
  # http — where a cookie marked secure is simply never sent back, so login
  # silently fails.
  plug :session

  defp session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(session_options()))
  end

  @doc false
  def session_options do
    Keyword.put(@session_options, :secure, Application.get_env(:fountain, :secure_cookie, false))
  end

  plug FountainWeb.Router
end
